/*
   Copyright (c) 2026 TidesDB Corp.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; version 2 of the License.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

/* the INSERT and DELETE data paths and their bulk-DML lifecycle: write_row inserts a row and its
   secondary/fts/spatial index entries (enforcing UNIQUE constraints), delete_row removes them, and
   the start/end bulk hooks plus maybe_bulk_commit flush a large statement's writes in bounded
   batches. update_row lives in ha_tidesdb_dml_update.cc; the TRUNCATE path delete_all_rows stays
   in ha_tidesdb.cc with the column-family config builders it depends on. */

#include "ha_tidesdb.h"

#include <ft_global.h>
#include <mysql/plugin.h>

#include <algorithm>
#include <cstring>
#include <string>
#include <vector>

#include "key.h"
#include "sql_class.h"
#include "src/core/fts_text.h"
#include "src/handler/ha_tidesdb_fts.h"
#include "src/handler/ha_tidesdb_internal.h"
#include "src/handler/ha_tidesdb_spatial.h"

/* ******************** write_row (INSERT) ******************** */

int ha_tidesdb::write_row_auto_increment(const uchar *buf [[maybe_unused]], bool &pk_auto_generated)
{
    /* If the PK field is 0/NULL, the server's update_auto_increment() will
       generate a unique value from our atomic counter.  We can skip the
       expensive PK uniqueness point-get in that case.
       Only safe when the auto-inc field is the ENTIRE PK (single-column).
       For composite PKs, auto-inc only guarantees uniqueness within
       the auto-inc column, not the full composite key. */
    if (table->next_number_field->val_int() == 0 && share->has_user_pk &&
        table->key_info[share->pk_index].user_defined_key_parts == 1)
        pk_auto_generated = true;
    int ai_err = update_auto_increment();
    if (ai_err) return ai_err;
    /* We keep the shared counter ahead of any explicitly-supplied value
       so that future auto-generated values don't collide. */
    ulonglong val = table->next_number_field->val_int();
    ulonglong cur = share->auto_inc_val.load(std::memory_order_relaxed);
    while (val > cur)
    {
        if (share->auto_inc_val.compare_exchange_weak(cur, val, std::memory_order_relaxed)) break;
    }
    return 0;
}

int ha_tidesdb::write_check_pk_unique(tidesdb_trx_t *trx, const uchar *dk, uint dk_len,
                                      const uchar *pk, uint pk_len, bool skip_pk_unique)
{
    /* We check PK uniqueness before inserting (TidesDB put overwrites silently).
       IODKU needs HA_ERR_FOUND_DUPP_KEY so the server can run the UPDATE clause.
       REPLACE INTO also needs it when secondary indexes exist (old index entries
       must be cleaned up via delete+reinsert).  When write_can_replace_ is set
       and the table has no secondary indexes, we skip the dup check entirely --
       tidesdb_txn_put will overwrite the old value, which is exactly what REPLACE
       wants, saving a full point-lookup per row.
       SET SESSION tidesdb_skip_unique_check=1 (bulk load) also bypasses this.
       When the PK was auto-generated by our O(1) atomic counter, the value is
       guaranteed unique (seeded from max existing value) -- skip the point-get. */
    if (!share->has_user_pk || skip_pk_unique ||
        (write_can_replace_ && share->num_secondary_indexes == 0))
        return 0;

    int ex = probe_pk_exists(trx, dk, dk_len);
    if (ex < 0) return -ex;
    if (ex)
    {
        note_dup_key(share->pk_index);
        memcpy(dup_ref, pk, pk_len);
        return HA_ERR_FOUND_DUPP_KEY;
    }
    return 0;
}

int ha_tidesdb::write_check_secondary_unique(const uchar *buf, tidesdb_txn_t *txn)
{
    /* We check UNIQUE secondary index uniqueness.  This honours the
       explicit tidesdb_skip_unique_check session contract but never the
       pk_auto_generated optimization, which only proves the primary key is
       unique and tells us nothing about secondary unique values. */
    if (!(share->num_secondary_indexes > 0 && !cached_skip_unique_)) return 0;

    for (uint i = 0; i < table->s->keys; i++)
    {
        if (share->has_user_pk && i == share->pk_index) continue;
        if (i >= share->idx_cfs.size() || !share->idx_cfs[i]) continue;
        if (share->idx_is_fts[i] || share->idx_is_spatial[i]) continue;
        if (!(table->key_info[i].flags & HA_NOSAME)) continue;

        /* SQL gives NULL no identity, so a UNIQUE index never constrains a row whose indexed value
           is NULL in any part.  Skip the check in that case, matching InnoDB and the update path;
           without this a second row with a NULL indexed value is wrongly rejected as a duplicate.
         */
        const my_ptrdiff_t ins_ptrdiff = (my_ptrdiff_t)(buf - table->record[0]);
        bool any_null = false;
        for (uint p = 0; p < table->key_info[i].user_defined_key_parts; p++)
        {
            Field *f = table->key_info[i].key_part[p].field;
            if (TDB_FIELD_IS_NULLABLE(f) && f->is_real_null(ins_ptrdiff))
            {
                any_null = true;
                break;
            }
        }
        if (any_null) continue;

        uchar idx_prefix[MAX_KEY_LENGTH];
        uint idx_prefix_len = make_comparable_key(
            &table->key_info[i], buf, table->key_info[i].user_defined_key_parts, idx_prefix);

        /* A UNIQUE secondary index rejects a row whose comparable index
           prefix already exists under a different pk.  Read the index cf
           through a fresh iterator each row: it merges the txn's buffered
           writes when created, so it sees earlier same-statement rows and
           committed data alike, whereas a reused iterator would carry a
           stale writeset snapshot and miss a same-statement duplicate. */
        tidesdb_iter_t *dup_iter = NULL;
        int irc = tdb_iter_new_blocking(ha_thd(), txn, share->idx_cfs[i], &dup_iter);
        if (irc != TDB_SUCCESS || !dup_iter)
        {
            /* Cannot safely skip the check without risking a silent UNIQUE
               violation, so propagate the error. */
            return tdb_rc_to_ha(irc, "write_row dup_iter_new");
        }
        tidesdb_iter_seek(dup_iter, idx_prefix, idx_prefix_len);
        bool is_dup = false;
        if (tidesdb_iter_valid(dup_iter))
        {
            uint8_t *fk = NULL;
            size_t fks = 0;
            tdb_owned_buf fk_g(fk);
            if (tidesdb_iter_key(dup_iter, &fk, &fks) == TDB_SUCCESS && fks >= idx_prefix_len &&
                memcmp(fk, idx_prefix, idx_prefix_len) == 0)
            {
                is_dup = true;
                /* Extract the pk suffix from the existing index key for dup_ref. */
                size_t dup_pk_len = fks - idx_prefix_len;
                if (dup_pk_len > 0 && dup_pk_len <= ref_length)
                    memcpy(dup_ref, fk + idx_prefix_len, dup_pk_len);
            }
        }
        tidesdb_iter_free(dup_iter);
        if (is_dup)
        {
            note_dup_key(i);
            return HA_ERR_FOUND_DUPP_KEY;
        }
    }
    return 0;
}

int ha_tidesdb::write_maintain_indexes(const uchar *buf, tidesdb_txn_t *txn, tidesdb_trx_t *trx,
                                       const uchar *pk, uint pk_len, time_t row_ttl)
{
    /* We maintain all secondary indexes in a single consolidated loop.
       Loop invariants are hoisted to avoid redundant pointer dereferences
       per iteration. Regular, FTS, and spatial indexes are dispatched
       inline to eliminate 2/3 of loop overhead vs 3 separate loops. */
    if (share->num_secondary_indexes == 0) return TDB_SUCCESS;

    const uint num_keys = table->s->keys;
    const bool has_user_pk = share->has_user_pk;
    const uint pk_index = share->pk_index;
    const size_t idx_cfs_sz = share->idx_cfs.size();

    for (uint i = 0; i < num_keys; i++)
    {
        if (has_user_pk && i == pk_index) continue;
        if (i >= idx_cfs_sz || !share->idx_cfs[i]) continue;

        const KEY *ki = &table->key_info[i];

        if (ki->algorithm == HA_KEY_ALG_FULLTEXT)
        {
            /* FTS index maintenance */
            const CHARSET_INFO *fts_cs = ki->key_part[0].field->charset();
            std::vector<std::string> fts_tokens;
            fts_extract_and_tokenize(table, ki, buf, fts_cs, fts_tokens);

            std::unordered_map<std::string, uint16> tf_map;
            for (auto &tok : fts_tokens) tf_map[tok]++;
            uint32 word_count = (uint32)fts_tokens.size();

            for (auto &kv : tf_map)
            {
                const auto &term = kv.first;
                auto &tf = kv.second;
                uchar fk[FTS_KEY_BUF_LEN];
                uint fk_len = fts_build_key(term.data(), (uint)term.size(), pk, pk_len, fk);
                uchar fv[FTS_VALUE_LEN];
                fts_build_value(tf, word_count, fv);
                int rc = tdb_txn_put_blocking(cached_thd_, txn, share->idx_cfs[i], fk, fk_len, fv,
                                              FTS_VALUE_LEN, row_ttl);
                if (rc != TDB_SUCCESS) return rc;
            }

            trx_fts_meta_accumulate(trx, share->cf, i, FTS_DOC_DELTA_ADD, (int64_t)word_count);
        }
        else if (is_spatial_index(ki))
        {
            /* Spatial index maintenance */
            Field *geom_field = ki->key_part[0].field;
            my_ptrdiff_t ptd = (my_ptrdiff_t)(buf - table->record[0]);
            if (ptd) geom_field->move_field_offset(ptd);
            String geom_str;
            geom_field->val_str(&geom_str, &geom_str);
            if (ptd) geom_field->move_field_offset(-ptd);

            double xmin, ymin, xmax, ymax;
            if (geom_str.length() > 0 &&
                spatial_compute_mbr((const uchar *)geom_str.ptr(), geom_str.length(), &xmin, &ymin,
                                    &xmax, &ymax))
            {
                double cx = (xmin + xmax) / MBR_CENTROID_DIV;
                double cy = (ymin + ymax) / MBR_CENTROID_DIV;
                uchar sk[SPATIAL_HILBERT_KEY_LEN + MAX_KEY_LENGTH];
                uint sk_len = spatial_build_key(cx, cy, pk, pk_len, sk);
                uchar sv[SPATIAL_MBR_VALUE_LEN];
                spatial_build_value(xmin, ymin, xmax, ymax, sv);
                int rc = tdb_txn_put_blocking(cached_thd_, txn, share->idx_cfs[i], sk, sk_len, sv,
                                              SPATIAL_MBR_VALUE_LEN, row_ttl);
                if (rc != TDB_SUCCESS) return rc;
            }
        }
        else
        {
            /* Regular secondary index maintenance */
            uchar ik[SEC_IDX_KEY_BUF_LEN];
            uint ik_len = sec_idx_key(i, buf, ik);
            int rc = tdb_txn_put_blocking(cached_thd_, txn, share->idx_cfs[i], ik, ik_len,
                                          &tdb_empty_val, sizeof(tdb_empty_val), row_ttl);
            if (rc != TDB_SUCCESS) return rc;
        }
    }
    return TDB_SUCCESS;
}

uint ha_tidesdb::write_build_pk(const uchar *buf, uchar *pk)
{
    if (share->has_user_pk) return pk_from_record(buf, pk);

    /* Hidden PK -- we generate next row-id */
    uint64_t row_id = share->next_row_id.fetch_add(1, std::memory_order_relaxed);
    encode_be64(row_id, pk);
    return HIDDEN_PK_SIZE;
}

int ha_tidesdb::bulk_flush_if_threshold(tidesdb_trx_t *trx, ha_rows weight)
{
    bulk_insert_ops_ += weight;
    if (bulk_insert_ops_ >= TIDESDB_BULK_INSERT_BATCH_OPS)
    {
        int mrc = maybe_bulk_commit(trx);
        if (mrc) return mrc;
        bulk_insert_ops_ = 0;
    }
    return 0;
}

int ha_tidesdb::write_row(TDB_ROW_IN *buf)
{
    DBUG_ENTER("ha_tidesdb::write_row");

    /* We need all columns readable for PK extraction, secondary index
       key building, serialization, and TTL computation. */
    TDB_COLUMN_MAP_SAVED old_map = TDB_USE_ALL_COLUMNS(table, read_set);

    bool pk_auto_generated = false; /* true when PK was auto-generated (guaranteed unique) */
    if (table->next_number_field && buf == table->record[0])
    {
        int ai_err = write_row_auto_increment(buf, pk_auto_generated);
        if (ai_err)
        {
            TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
            DBUG_RETURN(ai_err);
        }
    }

    uchar pk[MAX_KEY_LENGTH];
    uint pk_len = write_build_pk(buf, pk);

    uchar dk[DATA_KEY_BUF_LEN];
    uint dk_len = build_data_key(pk, pk_len, dk);

    const std::string &row_data = serialize_row(buf);
    if (share->encrypted && row_data.empty())
    {
        TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
        DBUG_RETURN(HA_ERR_GENERIC);
    }
    const uint8_t *row_ptr = (const uint8_t *)row_data.data();
    size_t row_len = row_data.size();

    /* Lazy txn -- we ensure stmt_txn exists on first data access */
    if (int erc = ensure_stmt_txn())
    {
        TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
        DBUG_RETURN(erc);
    }
    tidesdb_txn_t *txn = stmt_txn;
    stmt_txn_dirty = true;

    /* We use cached pointers from external_lock to avoid per-row overhead. */
    tidesdb_trx_t *trx = cached_trx_;
    if (trx) trx->dirty = true;
    note_modified_table(trx);

    cache_stmt_thdvars();

    bool skip_pk_unique = cached_skip_unique_ || pk_auto_generated;
    if (int prc = write_check_pk_unique(trx, dk, dk_len, pk, pk_len, skip_pk_unique))
    {
        TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
        DBUG_RETURN(prc);
    }

    if (int src = write_check_secondary_unique(buf, txn))
    {
        TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
        DBUG_RETURN(src);
    }

    /* Reject the insert when a declared foreign key points at a parent row that
       does not exist. */
    if (int frc = fk_check_child(buf))
    {
        TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
        DBUG_RETURN(frc);
    }

    /* We compute TTL when the table has TTL configured or the session overrides it.
       Uses cached_sess_ttl_ to avoid THDVAR + ha_thd() per row. */
    time_t row_ttl =
        (share->has_ttl || cached_sess_ttl_ > 0) ? compute_row_ttl(buf) : TIDESDB_TTL_NONE;

    int rc =
        tdb_txn_put_blocking(cached_thd_, txn, share->cf, dk, dk_len, row_ptr, row_len, row_ttl);
    if (rc != TDB_SUCCESS)
    {
        TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
        DBUG_RETURN(tdb_rc_to_ha(rc, "write_row"));
    }

    memcpy(current_pk_buf_, pk, pk_len);
    current_pk_len_ = pk_len;

    rc = write_maintain_indexes(buf, txn, trx, pk, pk_len, row_ttl);
    if (rc != TDB_SUCCESS)
    {
        TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
        DBUG_RETURN(tdb_rc_to_ha(rc, "write_row"));
    }

    /* We track ops for bulk insert batching (1 data + N secondary index puts) */
    if (in_bulk_insert_)
    {
        if (int mrc = bulk_flush_if_threshold(trx, 1 + share->num_secondary_indexes))
        {
            TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
            DBUG_RETURN(mrc);
        }
    }

    /* Commit happens in external_lock(F_UNLCK). */
    TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
    DBUG_RETURN(0);
}

/* ******************** delete_row (DELETE) ******************** */

int ha_tidesdb::delete_row(const uchar *buf)
{
    DBUG_ENTER("ha_tidesdb::delete_row");

    /* The read_set only needs widening when there are secondary indexes to
       maintain, since delete_maintain_indexes reads buf to rebuild their keys,
       or when this table is a foreign-key parent, since the referential check
       reads the referenced columns out of buf.  A primary-key-only table with
       neither deletes by current_pk_buf_ and never reads buf, so it skips the
       per-row bitmap flip entirely. */
    const bool flip_read_set = share->num_secondary_indexes != 0 || !share->fk_parent.empty();
    TDB_COLUMN_MAP_SAVED old_map = flip_read_set ? TDB_USE_ALL_COLUMNS(table, read_set) : nullptr;

    /* We use cached_trx_ from external_lock to avoid per-row hash lookups. */
    tidesdb_trx_t *trx = cached_trx_;

    cache_stmt_thdvars();

    {
        int erc = ensure_stmt_txn();
        if (erc)
        {
            if (flip_read_set) TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
            DBUG_RETURN(erc);
        }
    }
    tidesdb_txn_t *txn = stmt_txn;
    stmt_txn_dirty = true;
    if (trx)
    {
        trx->dirty = true;
    }
    note_modified_table(trx);

    /* Block the delete while a child row still references this parent row. */
    if (int frc = fk_enforce_parent_delete(buf))
    {
        if (flip_read_set) TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
        DBUG_RETURN(frc);
    }

    uchar dk[DATA_KEY_BUF_LEN];
    uint dk_len = build_data_key(current_pk_buf_, current_pk_len_, dk);

    /* Track the touched data-key range for the compact-after-range-delete reclaim and for the
       deferral's range tombstone.  Full data keys (KEY_NS_DATA + comparable_pk) compare here, so
       the bounds pass straight to tidesdb_compact_range or tidesdb_txn_delete_range. */
    if (in_bulk_delete_ && (bulk_delete_defer_ || cached_compact_after_range_delete_min_rows_ > 0))
    {
        const std::string this_key((const char *)dk, dk_len);
        if (bulk_delete_rows_ == 0)
        {
            bulk_delete_min_pk_ = this_key;
            bulk_delete_max_pk_ = this_key;
        }
        else
        {
            if (this_key < bulk_delete_min_pk_) bulk_delete_min_pk_ = this_key;
            if (this_key > bulk_delete_max_pk_) bulk_delete_max_pk_ = this_key;
        }
        bulk_delete_rows_++;
    }

    /* Defer the primary-row tombstone when this bulk delete is coalescing into a range tombstone,
       buffering the key rather than writing it so end_bulk_delete can turn the whole run into one
       tombstone.  A delete that outgrows the cap flushes the buffer to per-row tombstones and
       finishes on the ordinary path.  Otherwise write the tombstone now, as a single-row delete
       does. */
    int rc = TDB_SUCCESS;
    if (bulk_delete_defer_)
    {
        bulk_delete_keys_.emplace_back((const char *)dk, dk_len);
        if (bulk_delete_keys_.size() >= TIDESDB_BULK_DELETE_DEFER_CAP)
        {
            if (int frc = bulk_delete_flush_buffered(txn))
            {
                if (flip_read_set) TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
                DBUG_RETURN(frc);
            }
            bulk_delete_defer_ = false;
        }
    }
    else
    {
        rc = tdb_txn_delete_cf_blocking(cached_thd_, txn, share->cf, dk, dk_len,
                                        cached_single_delete_primary_);
        if (rc != TDB_SUCCESS)
        {
            if (flip_read_set) TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
            DBUG_RETURN(tdb_rc_to_ha(rc, "delete_row"));
        }
    }

    /* the primary-key row was removed above; now delete this row's entries from every
       secondary index so nothing dangles once the transaction commits. */
    rc = delete_maintain_indexes(buf, txn, trx);
    if (rc != TDB_SUCCESS)
    {
        if (flip_read_set) TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
        DBUG_RETURN(tdb_rc_to_ha(rc, "delete_row idx"));
    }

    /* Bulk DELETE mid-txn commit-- 1 data delete + num_secondary_indexes secondary-index deletes
       per row.  A deferring delete holds the buffered primary tombstones outside the txn, so a
       mid-txn commit would split them from the secondary deletes; skip it and let the cap bound
       memory instead. */
    if (in_bulk_delete_ && !bulk_delete_defer_)
    {
        if (int mrc = bulk_flush_if_threshold(trx, 1 + (ha_rows)share->num_secondary_indexes))
        {
            if (flip_read_set) TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
            DBUG_RETURN(mrc);
        }
    }

    if (flip_read_set) TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);
    DBUG_RETURN(0);
}

int ha_tidesdb::delete_maintain_indexes(const uchar *buf, tidesdb_txn_t *txn, tidesdb_trx_t *trx)
{
    /* We delete secondary index entries in a single consolidated dispatch loop.
       Regular, FTS, and spatial indexes are handled inline. */
    if (share->num_secondary_indexes == 0) return TDB_SUCCESS;

    const uint num_keys = table->s->keys;
    const bool has_user_pk = share->has_user_pk;
    const uint pk_index = share->pk_index;
    const size_t idx_cfs_sz = share->idx_cfs.size();

    for (uint i = 0; i < num_keys; i++)
    {
        if (has_user_pk && i == pk_index) continue;
        if (i >= idx_cfs_sz || !share->idx_cfs[i]) continue;

        KEY *ki = &table->key_info[i];

        if (share->idx_is_fts[i])
        {
            const CHARSET_INFO *fts_cs = ki->key_part[0].field->charset();
            std::vector<std::string> fts_tokens;
            fts_extract_and_tokenize(table, ki, buf, fts_cs, fts_tokens);

            std::unordered_map<std::string, uint16> tf_map;
            for (auto &tok : fts_tokens) tf_map[tok]++;
            uint32 word_count = (uint32)fts_tokens.size();

            for (auto &kv : tf_map)
            {
                const auto &term = kv.first;
                uchar fk[FTS_KEY_BUF_LEN];
                uint fk_len = fts_build_key(term.data(), (uint)term.size(), current_pk_buf_,
                                            current_pk_len_, fk);
                tdb_txn_delete_cf_blocking(cached_thd_, txn, share->idx_cfs[i], fk, fk_len, true);
            }

            trx_fts_meta_accumulate(trx, share->cf, i, FTS_DOC_DELTA_DEL, -(int64_t)word_count);
        }
        else if (share->idx_is_spatial[i])
        {
            Field *geom_field = ki->key_part[0].field;
            my_ptrdiff_t ptd = (my_ptrdiff_t)(buf - table->record[0]);
            if (ptd) geom_field->move_field_offset(ptd);
            String geom_str;
            geom_field->val_str(&geom_str, &geom_str);
            if (ptd) geom_field->move_field_offset(-ptd);

            double xmin, ymin, xmax, ymax;
            if (geom_str.length() > 0 &&
                spatial_compute_mbr((const uchar *)geom_str.ptr(), geom_str.length(), &xmin, &ymin,
                                    &xmax, &ymax))
            {
                double cx = (xmin + xmax) / MBR_CENTROID_DIV;
                double cy = (ymin + ymax) / MBR_CENTROID_DIV;
                uchar sk[SPATIAL_HILBERT_KEY_LEN + MAX_KEY_LENGTH];
                uint sk_len = spatial_build_key(cx, cy, current_pk_buf_, current_pk_len_, sk);
                tdb_txn_delete_cf_blocking(cached_thd_, txn, share->idx_cfs[i], sk, sk_len, true);
            }
        }
        else
        {
            uchar ik[SEC_IDX_KEY_BUF_LEN];
            uint ik_len = sec_idx_key(i, buf, ik);
            int rc =
                tdb_txn_delete_cf_blocking(cached_thd_, txn, share->idx_cfs[i], ik, ik_len, true);
            if (rc != TDB_SUCCESS) return rc;
        }
    }
    return TDB_SUCCESS;
}

/* ******************** Bulk DML ******************** */

/*
  Commit the current txn mid-statement and reset it with READ_COMMITTED so
  the next batch starts fresh.  Shared by bulk INSERT/UPDATE/DELETE once
  buffered ops cross TIDESDB_BULK_INSERT_BATCH_OPS, which bounds the memory the
  txn holds before commit since the whole write set lives in the ops array
  until then.  The reset drops to READ_COMMITTED so the read set does not grow
  across batches the way a higher isolation level would.

  Any cached iterators and dup-check iterators are invalidated, they hold
  references to MERGE_SOURCE_TXN_OPS that txn_reset clears.

  If the inner commit fails (e.g. transient TDB_ERR_UNKNOWN from a memtable
  rotation race) we must surface that to the SQL layer.  Returning
  0 here while the buffered ops are gone causes silent data loss -- the
  caller (write_row / update_row / delete_row) reports success even though
  up to TIDESDB_BULK_INSERT_BATCH_OPS rows were dropped on the floor.
  Instead, rollback to release the txn's state, swap in a fresh txn so the
  connection is left in a valid state for any retry, and propagate the
  error code so the server rolls the statement back and surfaces it to the
  client (typically as ER_ERROR_DURING_COMMIT).
*/
int ha_tidesdb::maybe_bulk_commit(tidesdb_trx_t *trx)
{
    if (!trx || !trx->txn) return 0;

    /* Folded FTS meta deltas have to land in the same txn as the row puts
       they account for, so flush them before the mid-statement commit. */
    int frc = flush_trx_fts_meta_pending(cached_thd_, trx);
    if (frc != TDB_SUCCESS) return tdb_rc_to_ha(frc, "bulk_commit fts_meta_flush");

    int crc = tdb_txn_commit_blocking(cached_thd_, trx->txn);
    if (crc != TDB_SUCCESS)
    {
        sql_print_error("[TIDESDB] bulk mid-commit failed rc=%d -- aborting statement to "
                        "avoid silent row loss",
                        crc);
        /* Release the txn's buffered state.  Even if rollback itself fails
           we still free+begin below so the connection is usable. */
        (void)tidesdb_txn_rollback(trx->txn);
        tidesdb_txn_free(trx->txn);
        trx->txn = NULL;
        /* Keep the statement's own isolation across the batch boundary.  Dropping to a level
           that does not validate writes would leave the rest of a large statement unchecked
           against concurrent writers, which is exactly the case a long statement is most
           exposed to. */
        int brc = tidesdb_txn_begin_with_isolation(tdb_global, trx->isolation_level, &trx->txn);
        if (brc != TDB_SUCCESS) return tdb_rc_to_ha(brc, "bulk_commit txn_begin(after_fail)");
        trx->txn_generation++;
        stmt_txn = trx->txn;
        scan_txn = trx->txn;
        if (scan_iter)
        {
            tidesdb_iter_free(scan_iter);
            scan_iter = NULL;
            scan_iter_cf_ = NULL;
            scan_iter_txn_ = NULL;
        }
        /* The txn was torn down, so the armed statement savepoint is void;
           disarm so a later statement rollback falls back to a full rollback
           rather than a stale partial one. */
        trx->stmt_savepoint_active = false;
        trx->stmt_fts_snapshot.clear();
        return tdb_rc_to_ha(crc, "bulk_commit");
    }

    int rrc = tidesdb_txn_reset(trx->txn, trx->isolation_level);
    if (rrc != TDB_SUCCESS)
    {
        sql_print_warning("[TIDESDB] bulk tidesdb_txn_reset failed (rc=%d), falling back to "
                          "free+begin",
                          rrc);
        tidesdb_txn_free(trx->txn);
        trx->txn = NULL;
        int rc = tidesdb_txn_begin_with_isolation(tdb_global, trx->isolation_level, &trx->txn);
        if (rc != TDB_SUCCESS) return tdb_rc_to_ha(rc, "bulk_commit txn_begin");
    }

    stmt_txn = trx->txn;
    trx->txn_generation++;

    /* The batch just went to storage and the reset left an empty transaction behind, so the
       connection has no uncommitted writes at this instant.  Saying otherwise makes the final
       commit act on an empty transaction: under two-phase commit the prepare of an empty batch is
       resolved as read-only by the library, and the commit that follows it is then handed an
       already-resolved transaction and fails with TDB_ERR_INVALID_ARGS.  The next row written by
       the rest of the statement sets this again. */
    trx->dirty = false;

    if (scan_iter)
    {
        tidesdb_iter_free(scan_iter);
        scan_iter = NULL;
        scan_iter_cf_ = NULL;
        scan_iter_txn_ = NULL;
    }
    scan_txn = trx->txn;
    /* The mid-statement commit reset the txn, so the armed statement savepoint
       no longer means anything.  Disarm it -- the remainder of this statement
       can no longer be rolled back atomically (the committed rows are durable),
       matching prior behavior. */
    trx->stmt_savepoint_active = false;
    trx->stmt_fts_snapshot.clear();
    return 0;
}

void ha_tidesdb::start_bulk_insert(TDB_BULK_INSERT_ARGS)
{
    in_bulk_insert_ = true;
    bulk_insert_ops_ = 0;
    /* Announce to the connection that this statement may commit part-way, so a scan opened on it
       -- the SELECT of an INSERT ... SELECT, the source of a copy-based ALTER -- reads under a
       snapshot transaction of its own instead of the one those commits reset. */
    if (cached_trx_) cached_trx_->stmt_piecewise = true;
}

int ha_tidesdb::end_bulk_insert()
{
    in_bulk_insert_ = false;
    return 0;
}

/*
  Declining the server's batched-update path, which is what InnoDB does and what the base class
  answers by default.

  Accepting it is not an optimisation, it is a correctness bug: handler::ha_update_row installs
  Update_rows_log_event::binlog_row_logging_function and logs the row it just wrote, while
  handler::ha_bulk_update_row does no binlogging at all -- it calls straight into the engine.  An
  engine that returns "batching supported" here therefore has its multi-row UPDATEs routed to a path
  that writes nothing to the binary log, and every such statement is silently lost to replication
  and to point-in-time recovery.  Nothing reports it; the replica simply never sees the change.

  What is given up by declining is the mid-statement flush that bulk_flush_if_threshold performs for
  INSERT and DELETE, so a large UPDATE now holds its whole statement in one library transaction.
  That is the same shape InnoDB has, and it is the cheaper of the two prices.
*/
bool ha_tidesdb::start_bulk_update()
{
    return true;
}

TDB_END_BULK_UPDATE_RET ha_tidesdb::end_bulk_update()
{
    in_bulk_update_ = false;
    TDB_END_BULK_UPDATE_RETURN(0);
}

/*
  the server calls bulk_update_row instead of update_row when start_bulk_update
  returned 0.  We don't actually buffer rows (TidesDB's txn is the buffer);
  we just delegate so the standard update_row path runs and its tail-side
  mid-commit block batches.  dup_key_found tracks duplicate-key collisions
  found in buffered-but-not-yet-applied rows -- since we apply immediately,
  it's always zero.
*/
/*
  Apply the rows bulk_update_row buffered.  Nothing is ever buffered here -- update_row applies each
  row into the library transaction as it arrives -- so this reports nothing outstanding and no
  duplicates.  The server calls it at the end of a batched UPDATE and treats the base class's
  "unsupported" answer as a statement failure, so an engine that opts into batching by returning
  false from start_bulk_update must answer here too.
*/
int ha_tidesdb::exec_bulk_update(TDB_DUPKEY_COUNT *dup_key_found)
{
    DBUG_ENTER("ha_tidesdb::exec_bulk_update");
    if (dup_key_found) *dup_key_found = 0;
    DBUG_RETURN(0);
}

int ha_tidesdb::bulk_update_row(const uchar *old_data, TDB_ROW_IN *new_data,
                                TDB_DUPKEY_COUNT *dup_key_found)
{
    DBUG_ENTER("ha_tidesdb::bulk_update_row");
    if (dup_key_found) *dup_key_found = 0;
    DBUG_RETURN(update_row(old_data, new_data));
}

/* build the smallest key strictly greater than every key beginning with the given data key, so a
   half-open range from the low bound to this successor covers an inclusive [min, max] span.  the
   last byte below 0xFF is incremented and the rest dropped; an all-0xFF key has no finite successor
   and returns false. */
static bool data_key_successor(const uchar *in, uint in_len, uchar *out, uint &out_len)
{
    if (!in || in_len == 0) return false;
    memcpy(out, in, in_len);
    for (uint i = in_len; i > 0; i--)
    {
        if ((uint8_t)out[i - 1] != KEY_INF_HI_BYTE)
        {
            out[i - 1]++;
            out_len = i;
            return true;
        }
    }
    return false;
}

/* count the live data-key rows in the half-open span [lo, hi) of a column family, used to confirm a
   deferred bulk delete removed every row the span holds before it collapses to a range tombstone.
 */
static int count_live_data_keys(THD *thd, tidesdb_txn_t *txn, tidesdb_column_family_t *cf,
                                const uchar *lo, uint lo_len, const uchar *hi, uint hi_len,
                                uint64_t *out_count)
{
    *out_count = 0;
    tidesdb_iter_t *it = NULL;
    int rc = tidesdb_iter_new_range(txn, cf, lo, lo_len, hi, hi_len, &it);
    if (rc != TDB_SUCCESS || !it) return rc != TDB_SUCCESS ? rc : TDB_ERR_IO;
    tidesdb_iter_seek_to_first(it);
    (void)thd;
    while (tidesdb_iter_valid(it))
    {
        uint8_t *k = NULL;
        size_t ks = 0;
        if (tidesdb_iter_key(it, &k, &ks) == TDB_SUCCESS)
        {
            tdb_owned_buf kg(k);
            if (is_data_key(k, ks)) (*out_count)++;
        }
        tidesdb_iter_next(it);
    }
    tidesdb_iter_free(it);
    return TDB_SUCCESS;
}

int ha_tidesdb::bulk_delete_flush_buffered(tidesdb_txn_t *txn)
{
    for (const std::string &k : bulk_delete_keys_)
    {
        int rc = tdb_txn_delete_cf_blocking(cached_thd_, txn, share->cf, (const uchar *)k.data(),
                                            (uint)k.size(), cached_single_delete_primary_);
        if (rc != TDB_SUCCESS) return tdb_rc_to_ha(rc, "bulk delete flush");
    }
    bulk_delete_keys_.clear();
    return 0;
}

bool ha_tidesdb::start_bulk_delete()
{
    in_bulk_delete_ = true;
    bulk_insert_ops_ = 0;
    if (cached_trx_) cached_trx_->stmt_piecewise = true;
    bulk_delete_rows_ = 0;
    bulk_delete_min_pk_.clear();
    bulk_delete_max_pk_.clear();
    bulk_delete_keys_.clear();
    /* defer primary-row tombstones into one range tombstone only for a plain user-pk table with no
       delete triggers, since deferral must not hide a row from a trigger reading the table
       mid-statement. */
    bulk_delete_defer_ = share && share->has_user_pk && share->cf && table->triggers == nullptr;
    return 0;
}

int ha_tidesdb::end_bulk_delete()
{
    in_bulk_delete_ = false;
    bool did_range_tombstone = false;

    /* Resolve a deferred bulk delete.  Every buffered key is a row this statement deleted, and with
       the tombstones deferred those rows are still live, so the live rows in [min, max] equal the
       buffered count exactly when the statement removed the whole span.  In that case one range
       tombstone replaces the run; a survivor (a residual filter, an IN-list gap, an ICP reject)
       leaves more live rows than buffered keys, so the buffer falls back to per-row tombstones. */
    if (bulk_delete_defer_ && !bulk_delete_keys_.empty())
    {
        if (int erc = ensure_stmt_txn()) return erc;
        tidesdb_txn_t *txn = stmt_txn;

        /* Only a run large enough to repay the completeness scan attempts a range tombstone.  When
           the live rows in [min, max] equal the buffered count, one range tombstone replaces the
           whole run; otherwise the buffer falls back to per-row tombstones. */
        bool ranged = false;
        if (bulk_delete_keys_.size() >= TIDESDB_BULK_DELETE_MIN_RANGE && share && share->cf &&
            !bulk_delete_min_pk_.empty() && !bulk_delete_max_pk_.empty())
        {
            uchar hi[DATA_KEY_BUF_LEN];
            uint hi_len = 0;
            uint64_t range_live = 0;
            if (data_key_successor((const uchar *)bulk_delete_max_pk_.data(),
                                   (uint)bulk_delete_max_pk_.size(), hi, hi_len) &&
                count_live_data_keys(
                    cached_thd_, txn, share->cf, (const uchar *)bulk_delete_min_pk_.data(),
                    (uint)bulk_delete_min_pk_.size(), hi, hi_len, &range_live) == TDB_SUCCESS &&
                range_live == bulk_delete_keys_.size() &&
                tidesdb_txn_delete_range(txn, share->cf,
                                         (const uint8_t *)bulk_delete_min_pk_.data(),
                                         bulk_delete_min_pk_.size(), hi, hi_len) == TDB_SUCCESS)
            {
                did_range_tombstone = true;
                ranged = true;
                stmt_txn_dirty = true;
                if (cached_trx_) cached_trx_->dirty = true;
                bulk_delete_keys_.clear();
            }
        }
        if (!ranged)
            if (int frc = bulk_delete_flush_buffered(txn)) return frc;
    }
    bulk_delete_keys_.clear();
    bulk_delete_defer_ = false;

    /* Auto compact-after-range-delete.  Threshold zero (default) keeps the previous behavior, no
       synchronous compaction at end-of-statement.  When the threshold is met we compact the
       observed [min_pk, max_pk] range on the primary CF, unless we already turned the run into a
       range tombstone, which reclaims the span on its own.  Secondary index tombstones are
       reclaimed by the per-CF tombstone_density_trigger. */
    if (!did_range_tombstone && cached_compact_after_range_delete_min_rows_ > 0 &&
        bulk_delete_rows_ >= cached_compact_after_range_delete_min_rows_ && share && share->cf &&
        !bulk_delete_min_pk_.empty() && !bulk_delete_max_pk_.empty())
    {
        int crc = tidesdb_compact_range(
            tdb_global, share->cf, (const uint8_t *)bulk_delete_min_pk_.data(),
            bulk_delete_min_pk_.size(), (const uint8_t *)bulk_delete_max_pk_.data(),
            bulk_delete_max_pk_.size());
        /* TDB_ERR_LOCKED is benign here -- another compaction is already
           running over a superset of our range, so our reclamation
           request will be absorbed by it.  Only log real failures. */
        if (crc != TDB_SUCCESS && crc != TDB_ERR_LOCKED)
        {
            sql_print_warning(
                "[TIDESDB] post-DELETE compact_range on '%s' failed (rows=%llu, err=%d)",
                share->cf_name.c_str(), (unsigned long long)bulk_delete_rows_, crc);
        }
    }

    bulk_delete_rows_ = 0;
    bulk_delete_min_pk_.clear();
    bulk_delete_max_pk_.clear();
    return 0;
}

/* ******************** Index Condition Pushdown (ICP) ******************** */

Item *ha_tidesdb::idx_cond_push(uint keyno, Item *idx_cond)
{
    DBUG_ENTER("ha_tidesdb::idx_cond_push");

    /* Only a secondary index scan takes it.
       What evaluates a pushed condition is icp_check_secondary, and the index scans call it only
       for a secondary index.  Taking the condition on a primary-key scan would mean returning NULL
       -- telling the server the engine evaluates all of it -- and setting
       in_range_check_pushed_down, telling it the engine also enforces the end of the range, while
       nothing on that path does either.  The server stops applying both on that promise and takes
       every row the scan hands back, so a primary-key range reads on to the end of the table and
       those extra rows come back as matches.  It is wrong quietly: they are real rows, just not the
       ones that were asked for.
       Nothing is given up by declining.  ICP earns its keep by evaluating an index entry before the
       base-row fetch it would otherwise need, and a primary-key scan already holds the row. */
    const bool is_pk = share && share->has_user_pk && keyno == share->pk_index;
    if (is_pk) DBUG_RETURN(idx_cond); /* not taken -- the server goes on evaluating it */

    pushed_idx_cond = idx_cond;
    pushed_idx_cond_keyno = keyno;
    in_range_check_pushed_down = true;

    DBUG_RETURN(NULL);
}

/* ******************** Multi-Range Read (MRR) ******************** */

/*
  Decide whether to accept a custom MRR strategy.  We only handle the case
  where every range the optimizer hands us is a full-key point lookup
  (UNIQUE_RANGE|EQ_RANGE) -- typically `WHERE col IN (v1, v2, ...)` on a
  PK or full-key unique index.  For mixed or true-range sequences we leave
  HA_MRR_USE_DEFAULT_IMPL set so the handler::multi_range_read_* default
  path runs unchanged.

  Iterating the sequence here consumes it; the server re-initialises it before
  calling multi_range_read_init, so probing is safe.
*/
ha_rows ha_tidesdb::multi_range_read_info_const(uint keyno, RANGE_SEQ_IF *seq, void *seq_init_param,
                                                uint n_ranges_arg, uint *bufsz, uint *mrr_mode,
                                                TDB_MRR_INFO_CONST_TAIL, Cost_estimate *cost)
{
    /* We compute the default cost + flags first so non-accepted sequences fall
       through to the server's MRR->read_range_first path with correct costing. */
    ha_rows rows =
        handler::multi_range_read_info_const(keyno, seq, seq_init_param, n_ranges_arg, bufsz,
                                             mrr_mode, TDB_MRR_INFO_CONST_TAIL_ARG, cost);
    if (rows == HA_POS_ERROR) return rows;

    /* Partitioned tables are served by ha_partition, which dispatches
       multi_range_read_* across child handlers using its own DS-MRR-backed
       logic.  If we clear HA_MRR_USE_DEFAULT_IMPL here, ha_partition's
       ordered-index-scan path ends up invoking our custom _next without
       the state its own ordering logic expects and crashes.  Refuse to
       accept MRR for partitioned tables -- the default path runs correctly. */
    if (TDB_TABLE_IS_PARTITIONED(table)) return rows;

    /* Probe the sequence, we accept only if every range is a full single-point
       equality.  A single non-point range forces us back to the default path. */
    KEY_MULTI_RANGE range;
    range_seq_t it = seq->init(seq_init_param, n_ranges_arg, *mrr_mode);
    bool all_point = true;
    uint count = 0;
    while (!seq->next(it, &range))
    {
        count++;
        if (!(range.range_flag & UNIQUE_RANGE) || (range.range_flag & NULL_RANGE) ||
            !(range.range_flag & EQ_RANGE))
        {
            all_point = false;
            break;
        }
    }

    /* We only accept when there are multiple ranges.  For a single point lookup
       the optimizer's eq_ref plan (plain index_read_map) is a better fit. */
    if (all_point && count >= MRR_ACCEPT_MIN_RANGES)
    {
        *mrr_mode &= ~HA_MRR_USE_DEFAULT_IMPL;
        *bufsz = 0; /* we use our own std::vector, not HANDLER_BUFFER */
    }
    return rows;
}

/*
  Build the sorted list of point lookups, or fall through to the default
  impl if HA_MRR_USE_DEFAULT_IMPL is still set.  Sorting by comparable
  bytes converts N scattered LSM seeks into a monotone stream -- much
  friendlier to the block cache and the merge-heap.
*/
int ha_tidesdb::multi_range_read_init(RANGE_SEQ_IF *seq, void *seq_init_param, uint n_ranges,
                                      uint mrr_mode, HANDLER_BUFFER *buf)
{
    DBUG_ENTER("ha_tidesdb::multi_range_read_init");

    mrr_custom_active_ = !(mrr_mode & HA_MRR_USE_DEFAULT_IMPL);
    if (!mrr_custom_active_)
        DBUG_RETURN(handler::multi_range_read_init(seq, seq_init_param, n_ranges, mrr_mode, buf));

    mrr_entries_.clear();
    mrr_next_idx_ = 0;
    mrr_keyno_ = active_index;
    mrr_no_assoc_ = MY_TEST(mrr_mode & HA_MRR_NO_ASSOCIATION);
    if (n_ranges > 0) mrr_entries_.reserve(n_ranges);

    KEY *ki = &table->key_info[mrr_keyno_];

    /* We need all columns readable while translating the caller's key_copy
       bytes into our comparable format (key_copy_to_comparable calls
       key_restore into record[1] and reads fields). */
    TDB_COLUMN_MAP_SAVED old_map = TDB_USE_ALL_COLUMNS(table, read_set);

    KEY_MULTI_RANGE range;
    range_seq_t it = seq->init(seq_init_param, n_ranges, mrr_mode);
    while (!seq->next(it, &range))
    {
        uchar comp[MAX_KEY_LENGTH];
        uint comp_len =
            key_copy_to_comparable(ki, range.start_key.key, range.start_key.length, comp);

        tdb_mrr_entry e;
        e.comp_key.assign((const char *)comp, comp_len);
        e.ptr = range.ptr;
        mrr_entries_.push_back(std::move(e));
    }

    TDB_RESTORE_COLUMN_MAP(table, read_set, old_map);

    std::sort(mrr_entries_.begin(), mrr_entries_.end(),
              [](const tdb_mrr_entry &a, const tdb_mrr_entry &b)
              { return a.comp_key < b.comp_key; });

    DBUG_RETURN(0);
}
